[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
example = "6mSByxsNqCRHXHuPmJdsgArE9uESE98YR6fREFomvJrv"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "make jest"
